# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='songentry',
            name='artist',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='songentry',
            name='title',
            field=models.TextField(),
        ),
    ]
